const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=$$('.stage'),steps=$$('.step');let current=0,activeMat=0,course=null;
function hasPptAI(){const s=JSON.parse(sessionStorage.getItem('jingbei-apis')||'null')?.ai2;return !!s?.base&&(s.auth==='none'||!!s.key)}
const library={
'二分':{goal:'理解二分查找的适用条件，能独立实现基础二分查找并处理边界',points:['从顺序查找引出效率问题','理解“有序”是二分查找的前提','掌握 left、right 与 mid 的变化过程','独立实现查找指定数字的程序','识别边界错误与死循环'],excluded:['STL：lower_bound / upper_bound','二分答案','浮点数二分'],task:'在有序数组中查找目标并输出下标；比较两种查找的次数；修复一段边界错误代码。'},
'循环':{goal:'理解循环的执行过程，能选择合适的循环结构完成重复任务',points:['从重复操作引出循环','掌握 for 循环的三个组成部分','理解循环变量与执行次数','使用循环完成累加与计数','识别死循环和边界错误'],excluded:['嵌套循环优化','递归','复杂枚举剪枝'],task:'输出指定范围的数字；计算 1 到 n 的和；修复一次少执行或多执行的循环。'},
'数组':{goal:'理解数组的连续存储和下标规则，能够遍历并处理一组数据',points:['用一组变量引出数组','声明、输入和访问数组元素','使用循环遍历数组','完成求和、最大值与统计','识别越界和下标偏移'],excluded:['二维数组','动态数组','STL vector'],task:'读入一组成绩并统计平均分与最高分；修复一段数组越界代码。'},
'搜索':{goal:'理解搜索状态与选择过程，能使用深度优先搜索解决基础枚举问题',points:['从穷举引出搜索树','定义状态、选择和终止条件','理解递归与回溯','完成基础 DFS 模板','识别重复状态与错误回溯'],excluded:['复杂剪枝','记忆化搜索','图上的高级搜索'],task:'枚举数字组合并输出满足条件的方案；画出搜索树；修复遗漏回溯的程序。'},
'动态规划':{goal:'理解状态、转移与初始条件，能完成一维动态规划入门题',points:['从重复计算引出动态规划','定义状态含义','寻找状态转移','设置初始值与遍历顺序','完成基础递推程序'],excluded:['区间动态规划','树形动态规划','状态压缩'],task:'用递推方法解决爬楼梯问题；填写状态表；比较递归与动态规划的计算次数。'}};
const generic=topic=>({goal:`理解${topic}的核心思想，能完成一项基础C++编程任务`,points:[`从实际问题引出${topic}`,`理解${topic}的核心概念`,`跟踪示例程序的执行过程`,`独立完成基础代码实现`,`识别并修正常见错误`],excluded:['超出CSP-J入门范围的高级技巧','复杂优化与证明','跨知识点综合难题'],task:`完成一道关于“${topic}”的基础编程题；解释关键代码；修复一段典型错误程序。`});
function templateFor(topic){return Object.entries(library).find(([k])=>topic.includes(k))?.[1]||generic(topic)}
function durationValue(){return Number($('#duration').value.match(/\d+/)?.[0]||90)}
function defaultSlides(topic,duration){const specs=[
['封面','建立主题与竞赛定位',topic,[`副标题：CSP-J专题课`,'关键词：理解 · 实现 · 调试'],'','主题关键词与抽象代码网格','大标题居中，右下角放课程信息','用一个真实问题开场，引出本课挑战'],
['目标','明确可检测的学习成果','学完这节课，你能够…',['说出核心概念和适用条件','跟踪关键变量的变化','独立完成基础C++实现','发现并修复一种常见错误'],'','四级能力阶梯','左侧目标清单，右侧能力阶梯','请学生选择自己最想达成的一项目标'],
['情境问题','制造认知冲突','如果数据很多，怎么办？',[`呈现一个与${topic}有关的真实问题`,'用已有方法估算操作次数','提出：能不能更快、更稳？'],'','场景图与数据规模数字卡片','上方问题，下方三步思考区','停留30秒，让学生先提出方案'],
['前置检查','确认学习条件','开始前，先检查这三点',['能读懂循环和条件判断','能使用数组保存数据','能跟踪变量值的变化'],'','三张勾选卡片','横向三卡片','若多数学生不熟悉，补充5分钟复习'],
['概念','建立准确心智模型',`${topic}的核心思想`,['用一句话给出定义','说明成立所需条件','说明每一步发生什么','指出最终得到什么'],'','流程图与关键条件标注','左文右图','先讲直觉，再给正式表述'],
['模拟','看见算法过程','手工模拟一次完整过程',['给出一组具体输入','逐步展示每轮状态','高亮变化的变量','在结束处标注结果'],'','逐轮状态表','上方数据，下方状态表','每一步先让学生预测，再揭示结果'],
['代码拆解','对应概念与代码','C++实现：先看骨架',['初始化：准备状态','循环条件：何时继续','核心操作：本轮做什么','状态更新：怎样进入下一轮'],'// 代码骨架\nwhile (条件) {\n    // 核心操作\n    // 更新状态\n}','代码分段着色并连线到解释','左侧代码，右侧四个标签','暂不展示完整答案，让学生口述缺失部分'],
['完整代码','形成可运行实现','完整程序与关键行说明',['输入与准备','核心算法','结果输出','特殊情况处理'],'// 放置完整、可编译的 C++17 程序','语法高亮，关键行加编号','代码占三分之二，右侧放行号说明','按初始化、判断、更新、输出分段讲解'],
['跟踪表','验证程序理解','代码是怎样运行的？',['填写每轮关键变量','记录判断结果','圈出状态变化','写出最终输出'],'','变量跟踪表：轮次 / 条件 / 状态 / 输出','整页表格，当前行高亮','教师逐行运行，学生同步填写'],
['易错点','预防典型错误','这三处最容易出错',['边界少一位或多一位','状态没有正确更新','循环条件造成遗漏或死循环'],'// 展示含错误的代码片段','错误代码、警告标记与反例输入','三张错误卡片','先展示错误现象，再让学生定位原因'],
['上机任务','明确任务与验收标准','课堂上机挑战',['基础：完成指定输入输出','进阶：处理边界数据','挑战：解释算法效率','验收：通过样例和自测'],'','任务阶梯与计时标记','左侧任务，右侧验收清单','提醒学生先写思路，再开始编码'],
['测试','培养调试意识','用哪些数据检查程序？',['最小规模数据','普通数据','边界位置数据','不存在或特殊情况'],'','测试数据表：输入 / 预期 / 检查目的','整页测试表','让学生补充一组自己的测试数据'],
['总结','收束知识并自评','一分钟回顾',['核心思想是什么？','成立条件是什么？','代码哪一步最关键？','现在能独立完成到哪一步？'],'','知识路径图与四级自评条','中心路径图，下方自评','请两名学生用自己的话总结'],
['作业','说明巩固与衔接','课后任务',['A组：巩固基础实现','B组：完成一种变式','C组：尝试竞赛挑战','预计完成时间：30分钟'],'','A/B/C分层任务卡','三栏卡片布局','明确必做与选做，预告下一课']];return specs.map((s,i)=>({page:i+1,type:s[0],objective:s[1],title:s[2],body:s[3],code:s[4],visual:s[5],layout:s[6],interaction:s[7],speaker_notes:s[7],minutes:i===0?2:Math.max(3,Math.round(duration/specs.length))}))}
function detailedDefaults(topic){return{'教师教案':[
{title:'一、学情分析',content:`授课对象为小学高年级或初中阶段的CSP-J学习者。学生已接触基础输入输出、变量、条件判断和循环，但把自然语言步骤转化为严谨程序的能力仍需训练。本课通过具体数据、手工模拟和代码跟踪建立对“${topic}”的理解。`},
{title:'二、教学目标',content:`1. 能用自己的语言解释${topic}的核心思想与适用条件。\n2. 能跟踪示例中关键变量的变化并说明每一步原因。\n3. 能独立写出一份可运行的C++基础实现。\n4. 能使用边界数据测试程序并修正常见错误。`},
{title:'三、重点与难点',content:`教学重点：${topic}的执行过程、关键条件和C++实现结构。\n教学难点：把过程中的状态变化对应到代码变量，并正确处理边界情况。`},
{title:'四、课前准备',content:'教师准备：演示数据、逐步状态表、可运行代码、错误代码和测试数据。\n学生准备：草稿纸、笔、C++17编程环境，并复习循环、条件判断及数组基础。'},
{title:'五、问题导入与教师话术',content:`教师展示一个与${topic}有关的真实任务：“如果数据规模扩大，我们原来的方法还合适吗？”先让学生独立思考30秒，再邀请两名学生说明方案。教师不立即评价答案，而是追问：方法成立需要什么条件？最坏情况下要做多少次操作？由此引出本课主题。`},
{title:'六、核心讲解流程',content:`先用一句话给出${topic}的直观解释，再明确适用条件；随后使用一组具体输入进行逐轮模拟，每轮记录判断、关键变量与剩余范围；完成模拟后，把每一步连接到C++代码中的初始化、循环条件、核心操作和状态更新。讲解过程中每一步都先让学生预测，再揭示结果。`},
{title:'七、上机活动与巡视要点',content:'学生先写出算法步骤，再完成基础程序。教师巡视时重点检查：循环条件是否正确、变量是否真正向终止状态移动、输出是否覆盖未找到或边界情况。对完成较快的学生增加一组极端数据，要求解释程序为什么仍然正确。'},
{title:'八、总结与评价',content:`请学生完成四句总结：${topic}解决什么问题；使用前要满足什么条件；代码中最关键的一步是什么；自己最容易错在哪里。教师根据口头回答、变量跟踪表、程序测试结果和错误修复情况判断是否达成目标。`}],
'学生讲义':[
{title:'学习目标',content:`学完本课，我能够解释${topic}的基本思想，跟踪关键变量变化，完成基础C++实现，并用边界数据检查程序。`},
{title:'核心概念',content:`${topic}不是需要死记的代码模板，而是一套“根据当前状态作出判断，再缩小或推进问题范围”的过程。学习时要同时关注适用条件、每一步做什么、状态怎样变化以及何时结束。`},
{title:'操作步骤',content:'第1步：读懂输入和目标。\n第2步：确定需要维护的状态或变量。\n第3步：写出继续执行的条件。\n第4步：完成本轮判断与操作。\n第5步：更新状态并检查是否结束。\n第6步：输出结果并测试边界情况。'},
{title:'C++代码骨架',content:'```cpp\n#include <bits/stdc++.h>\nusing namespace std;\nint main() {\n    // 1. 读入数据\n    // 2. 初始化关键变量\n    while (/* 继续条件 */) {\n        // 3. 本轮判断与操作\n        // 4. 更新状态\n    }\n    // 5. 输出结果\n    return 0;\n}\n```'},
{title:'手工模拟记录表',content:'请为每一轮记录：轮次、进入本轮前的关键变量、判断结果、本轮操作、更新后的变量、是否结束。不要只写最终答案。'},
{title:'易错点',content:'1. 没有检查算法适用条件。\n2. 循环边界少一位或多一位。\n3. 状态没有更新，导致死循环。\n4. 只测试普通数据，没有测试最小规模、边界位置和特殊情况。'},
{title:'课堂任务',content:`完成一道${topic}基础题：先写三到五行自然语言步骤，再编写程序；至少使用三组不同类型的数据测试，并在代码旁标出初始化、判断、更新和输出的位置。`},
{title:'学习自评',content:'□ 我能解释核心思想。\n□ 我能完成一次手工模拟。\n□ 我能独立写出基础代码。\n□ 我能说出至少两个易错点。\n我仍然不确定的问题：________________。'}],
'随堂练习':[
{title:'第1题｜概念判断',content:`判断：只要写出循环，就可以使用${topic}解决问题。\n答案：错误。\n解析：任何算法都有适用条件，必须先判断题目结构是否满足。`},
{title:'第2题｜步骤排序',content:'将“判断本轮状态、初始化变量、输出答案、更新状态”按程序执行顺序排列。\n答案：初始化变量 → 判断本轮状态 → 更新状态 → 输出答案。'},
{title:'第3题｜变量跟踪',content:'教师给出一组具体输入和前三轮运行过程，请填写每轮关键变量的值，并圈出发生变化的变量。\n答案要点：每轮记录必须与代码执行顺序一致，不能直接写最终值。'},
{title:'第4题｜代码阅读',content:'阅读课堂示例代码，回答循环在什么条件下继续、每轮修改了哪些变量、程序在什么情况下结束。\n答案要点：分别对应循环条件、状态更新和终止条件。'},
{title:'第5题｜补全代码',content:'补全初始化、循环条件和状态更新三处空白，使程序能够完成课堂示例任务。\n答案：以课堂确认后的完整代码为准；三处内容必须保持逻辑一致。'},
{title:'第6题｜错误修复',content:'给定一段可能死循环或遗漏边界数据的代码，找出错误并说明原因。\n答案要点：检查循环边界以及每个分支是否都会推动状态变化。'},
{title:'第7题｜测试设计',content:'设计普通数据、最小规模数据和边界数据各一组，写出预期输出以及该数据主要检查什么。\n评分标准：数据合法、预期正确、检查目的明确。'},
{title:'第8题｜上机编程',content:`独立完成一道${topic}基础题。要求：程序可在C++17下编译；通过给定样例；自测不少于三组；能够口头解释关键代码。`}],
'课后作业':[
{title:'A组1｜基础复现（必做）',content:`不看课堂代码，重新写出${topic}的基础实现，并在代码中用注释标出初始化、循环条件、核心操作和状态更新。\n答案标准：程序可编译，结构完整，能够通过普通与边界数据。`},
{title:'A组2｜过程说明（必做）',content:'选择一组输入，完整写出每轮关键变量和判断结果。\n答案标准：记录顺序与程序执行一致，最终结果正确。'},
{title:'B组1｜边界纠错（选做）',content:'修复教师提供的边界错误程序，并补充一组能让原程序出错的数据。\n答案要点：既要改对代码，也要说明反例为什么有效。'},
{title:'B组2｜条件变化（选做）',content:'当输入条件发生一种小变化时，说明原方法能否直接使用；若不能，需要修改哪一步。\n答案要点：先检查适用条件，再讨论代码修改。'},
{title:'C组｜竞赛挑战',content:`完成一道与${topic}相关的CSP-J入门题，记录第一次未通过的测试原因和最终修改。重点评价调试过程，不只评价是否通过。`},
{title:'提交要求与参考答案',content:'提交源代码、手工模拟记录和三组自测数据。参考答案以课堂完整代码结构为基础；教师批改时重点检查边界、状态更新、测试覆盖和解释是否清楚。'}],
'家长反馈':[
{title:'可直接发送的课堂反馈',content:`今天我们学习了“${topic}”。孩子通过问题分析、手工模拟、代码跟踪和上机练习，理解了算法的基本思路，并尝试把步骤转化为C++程序。本节课重点关注的不是背模板，而是能否解释每一步为什么这样做。`},
{title:'课堂表现与达成情况',content:'建议教师根据实际情况修改：孩子能够参与课堂讨论，并完成基础任务；在变量跟踪和边界检查方面表现较好。后续需要继续练习独立写出完整程序，以及在出错时主动使用测试数据定位问题。'},
{title:'课后任务与家长配合',content:'课后请完成分层作业中的必做题，预计用时30分钟。家长不需要直接讲解代码，可以请孩子用自己的话说明“这道题要解决什么、每一步做什么、怎样判断答案正确”。如果孩子能够清楚表达，说明理解正在形成。'},
{title:'下节课衔接',content:`下节课会在${topic}基础上增加一种变化或综合应用。请提醒孩子保留本次代码、错误记录和测试数据，下一节课会继续使用。`} ]}}
function enrichMaterials(topic,materials){const guidance={'教师教案':'\n\n实施要求：教师需要给出具体示例、连续追问和预期学生回答；每个环节结束时用一个可观察的学习证据判断是否继续。对未达标学生提供代码骨架，对提前完成者增加边界测试和解释任务。','学生讲义':'\n\n学习要求：请先独立写出预测，再运行程序核对；在空白处记录关键变量、判断结果、错误原因和修改依据。只写最终答案不算完成。','随堂练习':'\n\n作答要求：必须写出思考过程或变量变化。教师按“结论正确、过程完整、能够解释”三个维度评分，并在讲评时展示一个正确方案和一个典型错误。','课后作业':'\n\n提交要求：附源代码、至少四组自测数据和一次错误订正记录。教师批改时重点检查边界条件、状态更新、输出格式以及学生是否能解释为什么正确。','家长反馈':'\n\n使用说明：教师发送前请根据课堂观察补充一条具体表现和一项下一步建议，避免只给笼统评价；家长可让孩子口述思路，不需要代写代码。'},extra={'教师教案':[{title:'九、逐分钟流程与教师话术',content:`0—10分钟完成情境导入和前置检查；10—35分钟讲解${topic}并完成手工模拟；35—55分钟把步骤映射到C++代码；55—80分钟开展分层上机任务；80—90分钟纠错、出口检测和作业说明。每个阶段先提问、再让学生预测、最后揭示并解释。`},{title:'十、评价量规与课后反思',content:'概念理解25分、过程表达25分、代码实现30分、测试调试20分。课后记录学生集中困难、有效示例、上机完成率、典型错误、实际用时以及下一课需要补讲的内容。'}],'学生讲义':[{title:'变量跟踪与调试记录',content:'按“轮次—进入本轮前的变量—判断结果—执行语句—更新后的变量—输出”填写至少三轮。再记录一组普通数据、一组最小数据、一组临界数据和一组特殊数据的预期与实际结果。'},{title:'学习证据与自我解释',content:`不用代码，用自己的话说明${topic}解决什么问题、需要什么条件、每轮如何推进、为什么一定结束。再写出一个自己最容易犯的错误及避免方法。`}],'随堂练习':[{title:'综合题｜反例与纠错',content:'阅读一段含边界错误的程序，构造能让它出错的数据，写出原输出和正确输出，定位错误语句并完成修复。参考答案应同时说明反例有效的原因。'},{title:'综合题｜方法比较',content:`比较直接枚举和${topic}方法的适用条件、执行次数、实现难度与易错点。评分点：四个维度各2分，结论与理由一致2分。`}],'课后作业':[{title:'错误档案',content:'记录一次错误的现象、触发数据、根本原因、修改位置和修改后的验证结果。不能只写“粗心”，必须归类为初值、条件、边界、更新、下标或输出格式问题。'},{title:'讲题与自测',content:`用150—250字向同学解释${topic}，配一组小数据和逐轮过程；提交四组自测数据，分别覆盖普通、最小、临界和特殊情况。`}],'家长反馈':[{title:'个性化勾选记录',content:'课堂状态：□积极发言 □能跟随模拟 □能独立编码 □需要提示。能力表现：□概念清楚 □变量跟踪准确 □边界意识较好 □调试有耐心。教师勾选后补充一句具体课堂证据。'},{title:'家庭交流问题',content:'请孩子说明今天的程序完成什么任务、每一轮发生什么变化、程序何时停止、用哪组数据检查边界。家长以倾听和追问为主，不需要直接提供代码答案。'}]};const out={};for(const name of Object.keys(materials)){if(name==='随堂练习'||name==='课后作业'){const items=materials[name]||[];if(items.every(x=>String(x.content).includes('【题目】'))&&items.length){out[name]=items;continue}const bank=concreteQuestionMaterials(topic);if(!bank)throw new Error('该主题暂无完整本地题库，请配置文字AI生成具体题目');out[name]=bank[name];continue}out[name]=(materials[name]||[]).map(x=>({...x,content:`${x.content}${guidance[name]||''}`})).concat(extra[name]||[])}return out}
function buildCourse(){const topic=$('#topic').value.trim()||'未命名课程',duration=durationValue(),audience=$('#audience').value,type=$('.segmented .selected').textContent,t=templateFor(topic),times=[.09,.17,.19,.33,.13,.09].map(x=>Math.round(duration*x));times[3]+=duration-times.reduce((a,b)=>a+b,0);return{topic,duration,audience,type,goal:t.goal,points:t.points,excluded:t.excluded,task:t.task,times,pptSlides:defaultSlides(topic,duration),teachingMaterials:enrichMaterials(topic,detailedDefaults(topic)),updatedAt:new Date().toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}}
function courseRequest(){return{topic:$('#topic').value.trim()||'未命名课程',duration:durationValue(),audience:$('#audience').value,type:$('.segmented .selected').textContent,level:$('#studentLevel').value,prerequisites:$$('.form-card input')[1]?.value||'',requirements:$('.form-card textarea')?.value||''}}
const slideSchema={type:'object',properties:{page:{type:'integer'},type:{type:'string'},objective:{type:'string'},title:{type:'string'},body:{type:'array',items:{type:'string'}},code:{type:'string'},visual:{type:'string'},layout:{type:'string'},interaction:{type:'string'},speaker_notes:{type:'string'},minutes:{type:'integer'}},required:['page','type','objective','title','body','code','visual','layout','interaction','speaker_notes','minutes'],additionalProperties:false};
const materialSectionSchema={type:'object',properties:{title:{type:'string'},content:{type:'string'}},required:['title','content'],additionalProperties:false};
const courseSchema={type:'object',properties:{goal:{type:'string'},points:{type:'array',items:{type:'string'}},excluded:{type:'array',items:{type:'string'}},task:{type:'string'},pptSlides:{type:'array',items:slideSchema},teachingMaterials:{type:'object',properties:{lessonPlan:{type:'array',items:materialSectionSchema},studentHandout:{type:'array',items:materialSectionSchema},classPractice:{type:'array',items:materialSectionSchema},homework:{type:'array',items:materialSectionSchema},parentFeedback:{type:'array',items:materialSectionSchema}},required:['lessonPlan','studentHandout','classPractice','homework','parentFeedback'],additionalProperties:false}},required:['goal','points','excluded','task','pptSlides','teachingMaterials'],additionalProperties:false};
function aiPrompt(r){const count=r.duration<=60?'12到15':r.duration<=90?'16到20':'20到24';return `你是面向小学高年级和初中生的CSP-J信息学竞赛教学设计师。请生成供教师确认的完整备课内容，以及可以直接交给PPT制作AI的逐页详细大纲。课程主题：${r.topic}；对象：${r.audience}；水平：${r.level}；时长：${r.duration}分钟；类型：${r.type}；前置知识：${r.prerequisites||'未提供'}；补充要求：${r.requirements||'无'}。goal为一句可检测的教学目标；points为4到7个知识点；excluded为2到4个本课不涉及的进阶内容；task为课堂编程任务。teachingMaterials必须生成五类完整材料：lessonPlan至少8节，包含学情、目标、重难点、准备、逐环节时间、教师话术、上机指导、评价反思；studentHandout至少8节，包含概念、步骤、可编译或可补全代码、模拟表、易错点、任务和自评；classPractice至少8题，每题必须有题干、答案和解析；homework至少6项，包含A/B/C分层、答案或评分标准；parentFeedback至少4节，提供可直接发给家长的具体文字。每个section的content必须写完整内容，禁止只写目录或一句概括。pptSlides必须生成${count}页，覆盖导入、概念、过程模拟、代码拆解、完整代码、变量跟踪、易错点、上机任务、测试数据、总结和作业。每一页必须详细写明：page页码；type页面类型；objective本页教学目的；title页面标题；body页面上实际显示的完整文字列表；code需要展示的完整代码或片段，没有则为空字符串；visual具体图表或示意图内容；layout每个元素的位置、大小关系和版式；interaction课堂提问或互动；speaker_notes教师讲解提示；minutes预计分钟数。不得使用任何占位语。所有内容必须适龄并符合CSP-J范围。`}
function parseJsonText(text){const clean=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();return JSON.parse(clean)}
function mapTeachingMaterials(v,topic){validateQuestionMaterials(v);return enrichMaterials(topic,{'教师教案':v.lessonPlan,'学生讲义':v.studentHandout,'随堂练习':v.classPractice,'课后作业':v.homework,'家长反馈':v.parentFeedback})}
async function generateWithAI1(){const settings=JSON.parse(sessionStorage.getItem('jingbei-apis')||'null')?.ai1;if(!settings?.key)return null;const req=courseRequest(),headers={'Content-Type':'application/json','Authorization':`Bearer ${settings.key}`};let url,body,extract;if(settings.provider==='openai'){url=`${settings.base}/responses`;body={model:settings.model,store:false,max_output_tokens:24000,input:aiPrompt(req)+questionRequirements(req),text:{format:{type:'json_schema',name:'cspj_course_plan',strict:true,schema:courseSchema}}};extract=data=>data.output_text||data.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text}else{url=`${settings.base}/chat/completions`;body={model:settings.model,messages:[{role:'system',content:'你是严谨的CSP-J教学设计师，只输出JSON。'},{role:'user',content:aiPrompt(req)+questionRequirements(req)}],response_format:{type:'json_object'},temperature:.3,max_tokens:24000};extract=data=>data.choices?.[0]?.message?.content}const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)});if(!response.ok){let detail='';try{detail=(await response.json()).error?.message||''}catch{}throw new Error(detail||`请求失败（${response.status}）`)}const data=await response.json(),result=parseJsonText(extract(data));if(!result.goal||!Array.isArray(result.points)||!Array.isArray(result.pptSlides)||result.pptSlides.length<8||!result.teachingMaterials)throw new Error('模型返回的内容结构不完整');const fallback={...req,times:[.09,.17,.19,.33,.13,.09].map(x=>Math.round(req.duration*x)),updatedAt:new Date().toLocaleString('zh-CN')};return{...fallback,goal:result.goal,points:result.points.slice(0,7),excluded:(result.excluded||[]).slice(0,4),task:result.task,pptSlides:result.pptSlides,teachingMaterials:mapTeachingMaterials(result.teachingMaterials,req.topic),source:'AI 1'}}
function renderCourse(){if(!course)return;$('#goalText').textContent=course.goal;const lecture=course.times[0]+course.times[1]+course.times[2],practice=course.times[3],review=course.times[4]+course.times[5];$('#paceText').textContent=`讲解 ${lecture} 分钟 · 上机 ${practice} 分钟 · 纠错总结 ${review} 分钟`;$('#contentPoints').innerHTML=course.points.map(x=>`<li>${esc(x)}</li>`).join('');$('#excludedPoints').innerHTML=course.excluded.map(x=>`<li>${esc(x)}</li>`).join('');$('#taskText').textContent=course.task;$('#timelineTitle').textContent=`${course.duration}分钟课程安排`;$('#timelineTotal').textContent=course.duration;$('#timelineLimit').textContent=course.duration;const rows=[['问题导入',`为什么需要学习${course.topic}`,'观察案例并提出思路','产生学习动机'],['原理讲解',`${course.topic}的核心概念`,'纸上模拟关键过程','理解基本原理'],['代码演示','C++实现与变量跟踪','预测并核对运行结果','理解代码结构'],['上机练习','完成基础编程任务','独立编码与调试','掌握基本实现'],['错误分析','典型错误与边界情况','找错并修复','规避常见错误'],['总结作业','知识回顾与达标检测','自评并记录疑问','巩固迁移']];$('#blueprintBody').innerHTML=rows.map((r,i)=>`<tr contenteditable="true"><td>${esc(r[0])}</td><td>${course.times[i]}分钟</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${esc(r[3])}</td></tr>`).join('');const ppt=materials.find(x=>x.name==='PPT大纲'),lesson=materials.find(x=>x.name==='教师教案');ppt.title=`${course.topic} · ${(course.pptSlides||[]).length}页逐页大纲`;ppt.meta=`${(course.pptSlides||[]).length}页 · 待确认`;lesson.title=`教师教案 · ${course.duration}分钟`;renderMats()}
function syncFinish(){const card=$('.finish-card');if(!card)return;const topic=course?.topic||$('#topic').value.trim()||'未命名课程',audience=course?.audience||$('#audience').value,duration=course?.duration||durationValue(),type=course?.type||$('.segmented .selected').textContent,pptReady=hasPptAI(),title=card.querySelector('h2');title.textContent=topic;if(title.nextElementSibling)title.nextElementSibling.textContent=`${audience} · ${duration}分钟 · ${type}`;const pptItem=card.querySelector('.package-list > div:first-child');if(pptItem)pptItem.hidden=!pptReady;card.querySelectorAll('.package-list > div').forEach((item,i)=>{if(i>0){const name=['教师教案','学生讲义','随堂练习','课后作业','家长反馈'][i-1];item.querySelector('small').textContent=`${name==='随堂练习'||name==='课后作业'?'2份 PDF':'PDF'} · ${exportSections(name).length}${name==='随堂练习'||name==='课后作业'?'题':'节'}`}});const summary=$('[data-stage="5"] .heading p');if(summary)summary.textContent=pptReady?'六类材料使用同一份已确认蓝图，可以分别导出或下载完整备课包。':'五项文字材料已完成；未配置PPT AI，系统已自动跳过PPT制作。'}
function go(n){current=Math.max(0,Math.min(5,n));stages.forEach((s,i)=>s.classList.toggle('active',i===current));steps.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.toggle('done',i<current)});if(current===5)syncFinish();scrollTo({top:0,behavior:'smooth'});localStorage.setItem('jingbei-step',current)}
const materials=[
{name:'教师教案',meta:'待确认',title:'教师教案',items:['学情与前置知识','教学目标与重难点','问题导入话术','原理讲解步骤','代码演示与变量跟踪','上机任务指导','典型错误处理','课堂总结与反思']},
{name:'学生讲义',meta:'待审核',title:'学生讲义 · 课堂版',items:['本课目标','核心概念','算法流程','C++代码模板','易错点清单','课堂笔记区','上机任务','学习自评']},
{name:'随堂练习',meta:'待审核',title:'随堂练习 · 8题',items:['概念判断 × 2','代码阅读 × 2','补全代码 × 2','上机编程 × 1','错误修复 × 1']},
{name:'课后作业',meta:'待审核',title:'分层课后作业',items:['A组：基础巩固','A组：边界判断','B组：综合应用','B组：代码改错','C组：竞赛挑战','教师版答案与测试点']},
{name:'家长反馈',meta:'待审核',title:'家长反馈 · 通用模板',items:['今日学习内容','思维能力目标','课堂完成标准','课后任务与预计时间','家长配合建议','下节课预告']},
{name:'PPT大纲',meta:'待确认',title:'课程PPT大纲',items:['封面与学习目标','情境问题导入','旧方法与新方法对比','核心原理图解','手工模拟过程','关键变量说明','完整代码实现','课堂挑战与总结']}];
function renderSlideOutline(){const slides=course?.pptSlides||defaultSlides(course?.topic||'课程主题',course?.duration||90);return `<div class="outline-summary"><strong>共 ${slides.length} 页</strong><span>每页均包含可直接制作的文字、元素、版式与讲解说明</span></div><div class="slide-outline-list">${slides.map(s=>`<article class="slide-spec" contenteditable="true"><div class="slide-spec-head"><span class="page-index">${String(s.page).padStart(2,'0')}</span><div><small>${esc(s.type)} · ${Number(s.minutes)||0}分钟</small><h3>${esc(s.title)}</h3></div><span class="objective">本页目的：${esc(s.objective)}</span></div><div class="spec-grid"><section><b>页面文字</b><ul>${(s.body||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><b>视觉元素</b><p>${esc(s.visual)}</p></section><section><b>版式说明</b><p>${esc(s.layout)}</p></section><section><b>课堂互动</b><p>${esc(s.interaction)}</p></section>${s.code?`<section class="code-spec"><b>代码 / 数据</b><pre>${esc(s.code)}</pre></section>`:''}<section class="notes-spec"><b>教师讲解备注</b><p>${esc(s.speaker_notes)}</p></section></div></article>`).join('')}</div>`}
function renderMats(){const tabs=$('#materialTabs'),available=hasPptAI()?materials:materials.slice(0,5);if(activeMat>=available.length)activeMat=available.length-1;tabs.innerHTML=available.map((m,i)=>`<button class="mat-tab ${i===activeMat?'active':''}" data-i="${i}"><b>${m.name}</b><small>${m.meta}</small></button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(+b.dataset.i===5&&!materials.slice(0,5).every(x=>x.meta==='已确认')){show('请先确认前五项文字材料');return}activeMat=+b.dataset.i;renderMats()});const m=materials[activeMat],fallback=course?.teachingMaterials||enrichMaterials($('#topic')?.value||'课程主题',detailedDefaults($('#topic')?.value||'课程主题')),sections=course?.teachingMaterials?.[m.name]||fallback[m.name]||[];$('#matType').textContent=m.name;$('#matTitle').textContent=m.title;$('#materialContent').innerHTML=m.name==='PPT大纲'?renderSlideOutline():`<div class="rich-material">${sections.map((x,i)=>`<article class="rich-section" contenteditable="true"><div class="section-number">${String(i+1).padStart(2,'0')}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></div></article>`).join('')}</div>`}
function saveVersion(stage){if(!course)return;const saved=JSON.parse(localStorage.getItem('jingbei-courses')||'[]').filter(x=>x.topic!==course.topic);saved.unshift({...course,stage});localStorage.setItem('jingbei-courses',JSON.stringify(saved.slice(0,6)));renderRecent()}
function renderRecent(){const saved=JSON.parse(localStorage.getItem('jingbei-courses')||'[]'),box=$('#recentCourses');box.innerHTML=saved.length?saved.map((x,i)=>`<button class="recent-item" data-i="${i}"><strong>${x.topic}</strong><small>${x.audience} · ${x.duration}分钟 · ${x.updatedAt}</small></button>`).join(''):'<p class="empty-note">完成一次内容确认后，课程会出现在这里。</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{course=saved[+b.dataset.i];$('#topic').value=course.topic;$('#courseName').textContent=course.topic;renderCourse();go(1)})}
const toast=$('#toast');function show(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
$$('.next').forEach(b=>b.addEventListener('click',async()=>{if(current===3){const required=hasPptAI()?materials:materials.slice(0,5);if(!required.every(x=>x.meta==='已确认')){show(hasPptAI()?'请按顺序确认五项文字材料和PPT大纲':'请先确认全部五项文字材料');return}if(!hasPptAI()){go(5);show('未配置PPT AI，已跳过PPT制作');return}}if(current===0){const configured=!!JSON.parse(sessionStorage.getItem('jingbei-apis')||'null')?.ai1?.key;$('#generating').classList.add('show');$('#generating h3').textContent=configured?'AI 1 正在设计课程内容':'正在整理课程内容';$('#generating p').textContent=configured?'结合学生水平、前置知识和CSP-J范围生成方案…':'使用本地知识模板生成可编辑方案…';try{course=await generateWithAI1()||buildCourse();materials.forEach(m=>m.meta='待确认');activeMat=0;renderCourse();saveVersion(course.source?'AI内容草案':'本地内容草案');go(1);if(course.source)show('AI 1已生成内容方案，请教师审核')}catch(error){show(`生成未完成：${error.message}。请检查设置后重新生成`);console.warn('课程生成未完成');return}finally{$('#generating').classList.remove('show')}return}if(current===1)saveVersion('内容已确认');if(current===2)saveVersion('蓝图已确认');go(current+1)}));
$$('.prev').forEach(b=>b.addEventListener('click',()=>go(current-1)));steps.forEach((b,i)=>b.addEventListener('click',()=>go(i)));$$('.segmented button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
$('#topic').addEventListener('input',e=>$('#courseName').textContent=e.target.value||'未命名课程');$('#addPoint').onclick=()=>$('#contentPoints').insertAdjacentHTML('beforeend','<li>点击输入新的知识点</li>');
$('#approveBtn').onclick=()=>{$('#approveCheck').checked=true;const name=materials[activeMat].name;captureActiveMaterial(name);materials[activeMat].meta='已确认';saveVersion(`${name}已确认`);if(name==='家长反馈'&&!hasPptAI()){renderMats();show('五项文字材料已全部确认，可以直接完成备课');return}if(activeMat<materials.length-1){activeMat++;$('#approveCheck').checked=false;renderMats();show(name==='家长反馈'?'五项文字材料已确认，请最后审核PPT大纲':'本项已确认，已进入下一项')}else{renderMats();show('全部内容已确认，现在可以生成PPT')}};
$('#makePpt').onclick=e=>{const settings=JSON.parse(sessionStorage.getItem('jingbei-apis')||'null')?.ai2;if(!settings?.base||(!settings?.key&&settings?.auth!=='none')){openSettings();show('请先完成PPT生成服务的连接设置');return}const btn=e.currentTarget,job=$('#pptJob'),id=`PPT-${Date.now().toString().slice(-8)}`;btn.disabled=true;btn.textContent='正在提交生成任务…';job.className='ppt-job running';job.querySelector('strong').textContent=settings.mode==='sync'?'正在生成PPT':'任务已提交 · 正在生成';job.querySelector('small').textContent=`任务编号 ${id} · 使用${providerName(settings.provider)} · 仅发送已确认大纲`;setTimeout(()=>{btn.disabled=false;btn.textContent='重新生成PPT';job.className='ppt-job done';job.querySelector('strong').textContent='演示任务已完成';job.querySelector('small').textContent=`任务编号 ${id} · 接入真实接口后将在此提供${settings.format?.toUpperCase()||'PPTX'}下载`;show('任务流程验证完成，等待接入服务商真实接口')},1500)};
function captureActiveMaterial(name){if(!course||name==='PPT大纲')return;const sections=$$('.rich-section').map(x=>({title:x.querySelector('h3')?.innerText.trim()||'',content:x.querySelector('p')?.innerText.trim()||''}));if(sections.length){course.teachingMaterials=course.teachingMaterials||{};course.teachingMaterials[name]=sections}}
function exportSections(name){const topic=course?.topic||$('#topic').value||'课程主题',fallback=enrichMaterials(topic,detailedDefaults(topic));return course?.teachingMaterials?.[name]||fallback[name]||[]}
function teachingMarkdown(name,variant){const topic=course?.topic||$('#topic').value||'课程主题',meta=`${course?.audience||$('#audience').value} · ${course?.duration||durationValue()}分钟 · ${course?.type||$('.segmented .selected').textContent}`,label=name+(variant==='questions'?'（学生题目）':variant==='answers'?'（教师答案）':'');return lessonMarkdown(label,topic,meta,variant?splitQuestionSections(exportSections(name),variant):exportSections(name))}
function saveBlob(blob,fileName){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
let exportBusy=false;async function runPdfExport(action){if(exportBusy){show('PDF正在生成，请稍候');return}exportBusy=true;const buttons=$$('.package-list button').concat([$('.package')]),label=$('.package').textContent;buttons.forEach(b=>b.disabled=true);try{await action()}catch(e){show(`导出失败：${e.message}`)}finally{exportBusy=false;buttons.forEach(b=>b.disabled=false);$('.package').textContent=label}}async function downloadTeachingDoc(name,variant){return runPdfExport(async()=>{show(`正在生成${name}PDF…`);const topic=course?.topic||$('#topic').value||'课程主题',label=name+(variant==='questions'?'-学生题目':variant==='answers'?'-教师答案':''),bytes=await markdownToPdf(teachingMarkdown(name,variant),topic+'-'+label);saveBlob(new Blob([bytes],{type:'application/pdf'}),cleanFileName(topic)+'-'+label+'.pdf');show(`${label}PDF已开始下载`)})}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();function crc32(data){let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function le16(n){return new Uint8Array([n&255,(n>>>8)&255])}function le32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function zipBlob(files){const encoder=new TextEncoder(),local=[],central=[];let offset=0;for(const file of files){const name=encoder.encode(file.name),data=typeof file.data==='string'?encoder.encode(file.data):file.data,crc=crc32(data),header=new Uint8Array([...le32(0x04034b50),...le16(20),...le16(0x0800),...le16(0),...le16(0),...le16(0),...le32(crc),...le32(data.length),...le32(data.length),...le16(name.length),...le16(0),...name]);local.push(header,data);central.push(new Uint8Array([...le32(0x02014b50),...le16(20),...le16(20),...le16(0x0800),...le16(0),...le16(0),...le16(0),...le32(crc),...le32(data.length),...le32(data.length),...le16(name.length),...le16(0),...le16(0),...le16(0),...le16(0),...le32(0),...le32(offset),...name]));offset+=header.length+data.length}const size=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array([...le32(0x06054b50),...le16(0),...le16(0),...le16(files.length),...le16(files.length),...le32(size),...le32(offset),...le16(0)]);return new Blob([...local,...central,end],{type:'application/zip'})}
const exportNames=['教师教案','学生讲义','随堂练习','课后作业','家长反馈'];function exportEntries(){return exportNames.flatMap(name=>name==='随堂练习'||name==='课后作业'?[{name,variant:'questions',file:name+'-学生题目'},{name,variant:'answers',file:name+'-教师答案'}]:[{name,file:name}])}async function downloadCoursePackage(){return runPdfExport(async()=>{const topic=course?.topic||$('#topic').value||'课程主题',files=[],entries=exportEntries();for(let i=0;i<entries.length;i++){const entry=entries[i],md=teachingMarkdown(entry.name,entry.variant);$('.package').textContent=`正在生成${entry.file}PDF（${i+1}/${entries.length}）…`;files.push({name:`PDF/${entry.file}.pdf`,data:await markdownToPdf(md,topic+'-'+entry.file)},{name:`Markdown/${entry.file}.md`,data:md});await new Promise(resolve=>setTimeout(resolve,0))}if(course?.manusTask?.files?.length){const f=course.manusTask.files.find(x=>x.format==='pptx')||course.manusTask.files[0];files.push({name:'PPT/课堂PPT.'+f.format,data:await manusFileBytes(f)})}files.push({name:'课程包说明.md',data:`# ${topic}课程包\n\nPDF文件夹包含七份PDF：教师教案、学生讲义、随堂练习-学生题目、随堂练习-教师答案、课后作业-学生题目、课后作业-教师答案、家长反馈。\n\n学生题目保留题干、代码、输入输出和样例；教师答案保存参考答案、解析和评分标准。\n\nMarkdown文件夹包含对应的七份源文件。\n`});saveBlob(zipBlob(files),cleanFileName(topic)+'-课程包.zip');show('题目与答案分开的PDF课程包已开始下载')})}
$$('.package-list > div').forEach((item,i)=>{const button=item.querySelector('button');if(i===0){button.onclick=()=>show('课堂PPT需要由PPT AI生成后下载');return}const name=exportNames[i-1];if(name==='随堂练习'||name==='课后作业'){const actions=document.createElement('nav');actions.className='export-actions';actions.setAttribute('aria-label',name+'下载');button.replaceWith(actions);button.textContent='题目 PDF';button.onclick=()=>downloadTeachingDoc(name,'questions');const answers=document.createElement('button');answers.textContent='答案 PDF';answers.onclick=()=>downloadTeachingDoc(name,'answers');actions.append(button,answers)}else button.onclick=()=>downloadTeachingDoc(name)});$('.package').onclick=downloadCoursePackage;$('#resetBtn').onclick=()=>go(0);$('#newCourse').onclick=()=>go(0);
const settingsModal=$('#settingsModal'),providerDefaults={openai:{base:'https://api.openai.com/v1',model:'gpt-5-mini'},deepseek:{base:'https://api.deepseek.com/v1',model:'deepseek-flash'}},pptProviderNames={kimi:'Kimi / Moonshot',async:'通用异步PPT API',sync:'通用同步PPT API',custom:'自定义PPT服务'};
const providerName=v=>pptProviderNames[v]||'PPT服务';
const readApi1=()=>({provider:$('#ai1Provider').value,model:$('#ai1Model').value.trim(),base:$('#ai1Base').value.trim().replace(/\/$/,''),key:$('#ai1Key').value.trim()});
const readApi2=()=>({provider:$('#ai2Provider').value,profile:$('#ai2Profile').value,mode:$('#ai2Mode').value,base:$('#ai2Base').value.trim().replace(/\/$/,''),createPath:$('#ai2CreatePath').value.trim(),queryPath:$('#ai2QueryPath').value.trim(),auth:$('#ai2Auth').value,format:$('#ai2Format').value,key:$('#ai2Key').value.trim(),taskField:$('#ai2TaskField').value.trim(),statusField:$('#ai2StatusField').value.trim(),downloadField:$('#ai2DownloadField').value.trim()});
const setValue=(id,value)=>{if(value!==undefined&&value!==null&&$('#'+id))$('#'+id).value=value};
const fillApiForms=saved=>{const a=saved?.ai1,b=saved?.ai2;if(a){setValue('ai1Provider',a.provider);setValue('ai1Model',a.model);setValue('ai1Base',a.base);setValue('ai1Key',a.key)}if(b){['Provider','Profile','Mode','Base','CreatePath','QueryPath','Auth','Format','Key','TaskField','StatusField','DownloadField'].forEach(k=>setValue('ai2'+k,b[k.charAt(0).toLowerCase()+k.slice(1)]))}};
function openSettings(){const saved=JSON.parse(sessionStorage.getItem('jingbei-apis')||'null');fillApiForms(saved);settingsModal.classList.add('open');settingsModal.setAttribute('aria-hidden','false');setTimeout(()=>$('#ai1Provider').focus(),50)}
function closeSettings(){settingsModal.classList.remove('open');settingsModal.setAttribute('aria-hidden','true');$$('[data-toggle]').forEach(b=>{const input=$('#'+b.dataset.toggle);input.type='password';b.textContent='显示'})}
function updateApiState(){const saved=JSON.parse(sessionStorage.getItem('jingbei-apis')||'null'),status=$('#connectionStatus'),ai1Ready=!!saved?.ai1?.key,ai2Ready=!!saved?.ai2?.base&&(saved.ai2.auth==='none'||!!saved.ai2.key),count=[ai1Ready,ai2Ready].filter(Boolean).length;$('#apiState').textContent=count===2?'● 两个AI已配置':count===1?'● 已配置1个AI':'● 使用本地生成';status.classList.toggle('ready',count>0);status.querySelector('strong').textContent=count===2?'两套API均已配置':count===1?'已配置一套API':'尚未配置';status.querySelector('small').textContent=count===2?`AI 1：${saved.ai1.model} · AI 2：${providerName(saved.ai2.provider)}`:count===1?'未配置PPT AI时，将只生成前五项材料。':'可以只配置AI 1，系统会自动跳过PPT。';$('#pptProviderLabel').textContent=ai2Ready?`已连接：${providerName(saved.ai2.provider)}`:'尚未连接PPT服务';$('#toPpt').textContent=ai2Ready?'全部确认，生成PPT':'完成五项，跳过PPT';renderMats();if(current===5)syncFinish()}
$('#settingsBtn').onclick=openSettings;$('#openPptSettings').onclick=openSettings;$('#closeSettings').onclick=closeSettings;settingsModal.onclick=e=>{if(e.target===settingsModal)closeSettings()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSettings()});
$('#ai1Provider').onchange=e=>{const d=providerDefaults[e.target.value];if(d){$('#ai1Base').value=d.base;$('#ai1Model').value=d.model}};
$('#ai2Provider').onchange=e=>{const mode=e.target.value==='sync'?'sync':'async';$('#ai2Mode').value=mode;$('#pptProviderHint').textContent=e.target.value==='kimi'?'Kimi PPT 的公开产品能力与开放 API 并不等同；请按实际获得的接口文档填写端点。':'请根据服务商文档填写创建任务、查询任务路径和返回字段。'};
$$('[data-toggle]').forEach(b=>b.onclick=()=>{const input=$('#'+b.dataset.toggle),visible=input.type==='text';input.type=visible?'password':'text';b.textContent=visible?'显示':'隐藏'});
$('#saveApi').onclick=()=>{const ai1=readApi1(),ai2=readApi2();if(!ai1.key||!ai1.base||!ai1.model){show('请先完整填写AI 1的配置');return}for(const api of [ai1,ai2]){if(api.base){try{new URL(api.base)}catch{show('请检查API地址格式');return}}}if(ai2.base&&ai2.auth!=='none'&&!ai2.key){show('PPT服务需要填写API Key，或选择无需鉴权');return}if(ai2.base&&(!ai2.createPath||(ai2.mode==='async'&&!ai2.queryPath))){show('请完整填写PPT任务接口路径');return}sessionStorage.setItem('jingbei-apis',JSON.stringify({ai1,ai2}));sessionStorage.removeItem('jingbei-api');updateApiState();closeSettings();show('两套AI设置已保存到当前会话')};
$('#clearApi').onclick=()=>{sessionStorage.removeItem('jingbei-apis');sessionStorage.removeItem('jingbei-api');$('#ai1Key').value='';$('#ai2Key').value='';updateApiState();show('全部API配置已清除')};
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_lesson_preparation',title:'开始备课',description:'填写课程主题并生成可供教师确认的内容方案。',inputSchema:{type:'object',properties:{topic:{type:'string'},duration:{type:'number'}},required:['topic'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({topic,duration}){$('#topic').value=topic;$('#courseName').textContent=topic;if(duration){const o=[...$('#duration').options].find(x=>x.textContent.startsWith(duration));if(o)$('#duration').value=o.value}course=buildCourse();renderCourse();saveVersion('内容草案');go(1);return{topic,step:'内容确认'}}})}catch(e){}}
renderMats();renderRecent();updateApiState();go(Number(localStorage.getItem('jingbei-step')||0));
